### ISSUE TITLE
Possible issue with ipykernel or tornado event loop

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#361]
Seen in stdout (NotebookApp log) with commit 006317412500debfc58a1a806c43f050069b02d6 but think I've seen this since #350 was merged.  Not sure what the implications are yet but thought I'd log this anyway.

```
[W 15:48:52.300 NotebookApp] Notebook docs/MuMoTuserManual.ipynb is not trusted
[I 15:48:54.242 NotebookApp] Kernel started: 6b285d9f-7384-4e59-a3b1-81d10ee3b175
ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x7fbc0855c8c0>)
Traceback (most recent call last):
  File "/home/will/rse/code/mumot/mumot.git/.tox/py37/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/will/rse/code/mumot/mumot.git/.tox/py37/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 314, in advance_eventloop
    eventloop(self)
TypeError: 'NoneType' object is not callable
```

**Comment by jarmarshall** [comment]
OK - we unpinned tornado and ipykernel in #350 so that's a likely cause - never seen this error before...

**Comment by willfurnass** [comment]
Updated dependencies in #398; will close now and can reopen if necessary.
