### ISSUE TITLE
ipywidgets erroneously removed from list of deps (was: RTD builds are failing with v1.1.0)

### ISSUE THREAD

**Issue by willfurnass** [DiODeProject/MuMoT#368]
From https://readthedocs.org/projects/mumot/builds/:

```
Running Sphinx v1.8.5

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/envs/latest/lib/python3.6/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/envs/latest/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/checkouts/latest/docs/source/conf.py", line 70, in <module>
    import mumot
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/checkouts/latest/mumot/__init__.py", line 36, in <module>
    from .models import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/checkouts/latest/mumot/models.py", line 30, in <module>
    from . import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/mumot/checkouts/latest/mumot/controllers.py", line 6, in <module>
    import ipywidgets.widgets as widgets
ModuleNotFoundError: No module named 'ipywidgets'
```

Travis was able to build the docs for the v1.1.0 tagged commit, so I suspec that our RTD config or possibly RTD infrastructure is at fault.

**Comment by willfurnass** [comment]
Ah, I hastily removed ipywidgets from setup.py - readding via PR #369 then will tag release 1.1.1 before pushing new builds to PyPI.

**Comment by willfurnass** [comment]
Done
